### PR TITLE
Fixes the poweron functionality for Xbox

### PR DESCRIPTION
**Pull request by rkokkelk**
Uses the fixed functionality of the xbox-on addon, see issue [#9](https://github.com/arcreative/xbox-on/issues/9). Added an option dictionary.

### CODE REVIEW

**Comment by WeeJeWel** [comment]
@rkokkelk I've noticed that I'm very busy. In the meantime I've also sold my Xbox One. Would you be interested in taking over responsibility for the repo & app?

**Comment by rkokkelk** [comment]
Yeah, sound great. I'm definitely interested.

**Comment by WeeJeWel** [comment]
Great! What's your Athom ID? (In the URL at https://accounts.athom.com/)

**Comment by WeeJeWel** [comment]
Never mind, got it already :) 

I've made you owner of the app: https://apps.athom.com/app/net.weejewel.xboxone

Please fork this repo and update from there. Thank you and good luck!

**Pull request closed without merging**
